# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f33408fba4f1c7bf130e64b84e5834d1371d6e1287661e6b9e327ac0272f35f3a7abfc8a72ba31125351bca0db704cd4efd0a79e0af78a93c9e08078ef056d3

test:
  secret_key_base: bf15c032dc633096c17b7a52d043e03605ec2ee263a7008fc03e9f9fb5482c6d098a17073623ffbd1e1f83da6ac86b8f66ab8d77150dbcdf9c3bd442011499d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
